### ISSUE TITLE
TypeError: callback.call is not a function

### ISSUE THREAD

**Issue by lebence** [kopiro/homebridge-tapo-camera#100]
**Describe The Bug:**
After initalizing cameras my homebridge shutting down.

**Logs:**

```
[12/4/2023, 11:40:44 AM] TypeError: callback.call is not a function
    at Cam.<anonymous> (/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:309:14)
    at parseSOAPString (/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/utils.js:108:3)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/cam.js:297:4)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[12/4/2023, 11:40:44 AM] Got SIGTERM, shutting down Homebridge...
[12/4/2023, 11:40:44 AM] TypeError: callback.call is not a function
    at Cam.<anonymous> (/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:309:14)
    at parseSOAPString (/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/utils.js:108:3)
    at IncomingMessage.<anonymous> (/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/cam.js:297:4)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1368:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Plugin Config:**

```json
{
            "cameras": [
                {
                    "name": "balcony",
                    "ipAddress": " ---",
                    "password": "---",
                    "streamUser": "---",
                    "streamPassword": "---",
                    "disableAlarmAccessory": true
                },
                {
                    "name": "garden",
                    "ipAddress": "---",
                    "password": "---",
                    "streamUser": "---",
                    "streamPassword": "---",
                    "disableAlarmAccessory": true
                }
            ],
            "platform": "tapo-camera"
        },
```

**Environment:**

* **Plugin Version**: 2.3.3
* **Homebridge Version**: newest
* **Node.js Version**: 18.18.2
* **NPM Version**: 9.8.1
* **Operating System**: Docker (22.04.3 LTS)

**Comment by ColinPascoe** [comment]
I upgraded to latest Docker Homebridge version and latest Plugin Version and I am also now getting the same error as above.

**Comment by ppapajohn** [comment]
Hi all, 
+1 with the exact same issue. My only difference is in the Node.js version but I guess this is not important (i.e. I have v20.10.0). 

Best Regards,
Panos

**Comment by themfinger** [comment]
+1

**Comment by harrisonratcliffe** [comment]
Having the same issue.

**Comment by eliteladen** [comment]
Same problem here

**Comment by anthonydb06** [comment]
Up … 
Does anyone manage to fix this callback error which clauses the plugin to reboot in a loop …

**Comment by kopiro** [comment]
Try latest version please 
https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.3.4

**Comment by ppapajohn** [comment]
> Try latest version please 
> 
> https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.3.4

Thanks @kopiro! Just tested it and it works seamlessly.
