### ISSUE TITLE
TypeError: callback.call is not a function

### ISSUE THREAD

**Issue by ppapajohn** [kopiro/homebridge-tapo-camera#102]
Hi all, 
Thank you very much for fixing the password encryption bug. After upgrading to version 2.3.3 I get the following error which makes the plugin go on an infinite loop of restarting (practically it stays online for 10, 15 seconds, and then restarts): 

[12/5/2023, 6:01:34 AM] [homebridge-tapo-camera] Launched child bridge with PID 382777
[12/5/2023, 6:01:34 AM] Registering platform 'homebridge-tapo-camera.tapo-camera'
[12/5/2023, 6:01:34 AM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.3.3 child bridge successfully
[12/5/2023, 6:01:34 AM] Loaded 0 cached accessories from cachedAccessories.0E7DF481EFD1.
[12/5/2023, 6:01:34 AM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-tapo-camera) is running on port 54797.
[12/5/2023, 6:01:35 AM] IPC01 5652 is running on port 38927.
[12/5/2023, 6:01:35 AM] Please add [IPC01 5652] manually in Home app. Setup Code: 888-66-888
[12/5/2023, 6:01:35 AM] IPC02 383B is running on port 35763.
[12/5/2023, 6:01:35 AM] Please add [IPC02 383B] manually in Home app. Setup Code: 888-66-888

/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:309
                                callback.call(this, err, data, xml);
             ^
TypeError: callback.call is not a function
    at Cam.<anonymous> (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:309:14)
    at parseSOAPString (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/utils.js:108:3)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/cam.js:297:4)
    at IncomingMessage.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1589:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)

In advance, thank you once again for the amazing work and plugin. 

Best Regards,
Panos

**Comment by ppapajohn** [comment]
I just noticed that issue #100 is exactly the same, so I think you can delete this. Apologies for not noticing this earlier.
