### ISSUE TITLE
Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'response')

### ISSUE THREAD

**Issue by lebence** [kopiro/homebridge-tapo-camera#106]
**Describe The Bug:**
I get this error constantly, twice in a minute. I think this does not affect the proper functioning.I think this error is exists because of the newest C320WS firmware.

**Logs:**

```
[12/12/2023, 7:41:21 AM] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'response')
    at /homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:446:42
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStatus (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)
```

**Plugin Config:**

```json
{
            "cameras": [
                {
                    "name": "balcony",
                    "ipAddress": " ---",
                    "password": "---",
                    "streamUser": "---",
                    "streamPassword": "---",
                    "disableAlarmAccessory": true
                },
                {
                    "name": "garden",
                    "ipAddress": "---",
                    "password": "---",
                    "streamUser": "---",
                    "streamPassword": "---",
                    "disableAlarmAccessory": true
                }
            ],
            "platform": "tapo-camera"
        }
```

**Environment:**

Plugin Version: 2.3.4
Homebridge Version: newest
Node.js Version: 20.10.0
NPM Version: 9.8.1
Operating System: Docker (22.04.3 LTS)

**Comment by leslie220663** [comment]
Samne problem here and it's driven me insane. Simply cannot fix it

**Comment by leslie220663** [comment]
BTW, i'm getting the error on a raspberry Pi homebridge

**Comment by midnightcomesonce** [comment]
Getting the same error message here also on a Pi.

**Comment by lebence** [comment]
This problem is still available:

`
[2/22/2024, 10:27:41 AM] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'response')
    at /homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:446:42
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStatus (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)
[2/22/2024, 10:27:42 AM] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'response')
    at /homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:446:42
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStatus (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)
`

**Comment by GiffelDK** [comment]
Also having this issue:

[homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Invalid device confirm
    at TAPOCamera.refreshStok (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:205:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:335:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:415:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)

**Comment by kopiro** [comment]
I'll take a look now.

**Comment by RemiWest** [comment]
4 cameras Tapo c310.

[02/05/2024, 15:33:37] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Invalid device confirm
    at TAPOCamera.refreshStok (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:205:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:335:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:415:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)
[02/05/2024, 15:33:43] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Invalid device confirm
    at TAPOCamera.refreshStok (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:205:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:335:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:415:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)
[02/05/2024, 15:33:44] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Invalid device confirm
    at TAPOCamera.refreshStok (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:205:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:335:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:415:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)

**Comment by kopiro** [comment]
Hey, please update to https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.4.5 where I added more debug logs and post your logs again.

**Comment by kopiro** [comment]
Update: you may be affected by [this issue](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551). Please follow [this guide](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/blob/main/add_camera_with_new_firmware.md) on how to fix it.
