### ISSUE TITLE
Impossible to add v2.3.4 TAPO Camera plugin in Homebridge

### ISSUE THREAD

**Issue by r4z8rt** [kopiro/homebridge-tapo-camera#118]
**Describe Your Problem:**
When I try to install the v2.3.4, I have this error message :
```
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
```

**Logs:**

```
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\vince\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@10.4.0
2 info using node@v20.11.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:C:\Users\vince\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 5ms
6 timing config:load:builtin Completed in 5ms
7 timing config:load:cli Completed in 3ms
8 warn config global-style This option has been deprecated in favor of `--install-strategy=shallow`
9 timing config:load:env Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:C:\WINDOWS\system32\config\systemprofile\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\vince\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 14ms
17 timing npm:load:configload Completed in 14ms
18 timing config:load:flatten Completed in 3ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install homebridge-tapo-camera@2.3.4
22 verbose argv "install" "--global" "homebridge-tapo-camera@2.3.4"
23 timing npm:load:setTitle Completed in 2ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2024-01-28T19_12_55_449Z-
26 verbose logfile C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2024-01-28T19_12_55_449Z-debug-0.log
27 timing npm:load:logFile Completed in 12ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 66ms
31 timing config:load:flatten Completed in 0ms
32 timing arborist:ctor Completed in 1ms
33 silly logfile start cleaning logs, removing 2 files
34 timing idealTree:init Completed in 6ms
35 timing idealTree:userRequests Completed in 5ms
36 silly idealTree buildDeps
37 silly fetch manifest homebridge-tapo-camera@2.3.4
38 silly logfile done cleaning log files
39 http fetch GET 200 https://registry.npmjs.org/homebridge-tapo-camera 944ms (cache revalidated)
40 silly placeDep ROOT homebridge-tapo-camera@2.3.4 OK for:  want: 2.3.4
41 silly fetch manifest homebridge-camera-ffmpeg@^3.1.4
42 silly fetch manifest node-fetch@^2.7.0
43 silly fetch manifest onvif@github:agsh/onvif
44 http fetch GET 200 https://registry.npmjs.org/node-fetch 821ms (cache revalidated)
45 http fetch GET 200 https://registry.npmjs.org/homebridge-camera-ffmpeg 906ms (cache revalidated)
46 timing idealTree:#root Completed in 1870ms
47 silly fetch manifest encoding@^0.1.0
48 http fetch GET 200 https://registry.npmjs.org/encoding 51ms (cache revalidated)
49 silly placeDep node_modules/homebridge-tapo-camera homebridge-camera-ffmpeg@3.1.4 OK for: homebridge-tapo-camera@2.3.4 want: ^3.1.4
50 silly placeDep node_modules/homebridge-tapo-camera node-fetch@2.7.0 OK for: homebridge-tapo-camera@2.3.4 want: ^2.7.0
51 silly placeDep node_modules/homebridge-tapo-camera onvif@ OK for: homebridge-tapo-camera@2.3.4 want: github:agsh/onvif
52 silly fetch manifest ffmpeg-for-homebridge@^0.0.9
53 silly fetch manifest mqtt@4.2.8
54 silly fetch manifest pick-port@^1.0.0
55 silly fetch manifest whatwg-url@^5.0.0
56 http fetch GET 200 https://registry.npmjs.org/mqtt 798ms (cache revalidated)
57 http fetch GET 200 https://registry.npmjs.org/ffmpeg-for-homebridge 832ms (cache revalidated)
58 http fetch GET 200 https://registry.npmjs.org/whatwg-url 842ms (cache revalidated)
59 http fetch GET 200 https://registry.npmjs.org/pick-port 858ms (cache revalidated)
60 timing idealTree:node_modules/homebridge-tapo-camera Completed in 921ms
61 silly placeDep node_modules/homebridge-tapo-camera ffmpeg-for-homebridge@0.0.9 OK for: homebridge-camera-ffmpeg@3.1.4 want: ^0.0.9
62 silly placeDep node_modules/homebridge-tapo-camera mqtt@4.2.8 OK for: homebridge-camera-ffmpeg@3.1.4 want: 4.2.8
63 silly placeDep node_modules/homebridge-tapo-camera pick-port@1.0.1 OK for: homebridge-camera-ffmpeg@3.1.4 want: ^1.0.0
64 silly fetch manifest detect-libc@^1.0.3
65 silly fetch manifest dotenv@^8.2.0
66 silly fetch manifest mkdirp@^1.0.3
67 silly fetch manifest simple-get@^3.1.0
68 silly fetch manifest tar@^6.0.1
69 silly fetch manifest commist@^1.0.0
70 silly fetch manifest concat-stream@^2.0.0
71 http fetch GET 200 https://registry.npmjs.org/mkdirp 66ms (cache revalidated)
72 silly fetch manifest debug@^4.1.1
73 http fetch GET 200 https://registry.npmjs.org/dotenv 84ms (cache revalidated)
74 silly fetch manifest duplexify@^4.1.1
75 http fetch GET 200 https://registry.npmjs.org/concat-stream 122ms (cache revalidated)
76 silly fetch manifest help-me@^3.0.0
77 http fetch GET 200 https://registry.npmjs.org/debug 65ms (cache revalidated)
78 silly fetch manifest inherits@^2.0.3
79 http fetch GET 200 https://registry.npmjs.org/tar 148ms (cache revalidated)
80 silly fetch manifest minimist@^1.2.5
81 http fetch GET 200 https://registry.npmjs.org/minimist 81ms (cache revalidated)
82 silly fetch manifest mqtt-packet@^6.8.0
83 http fetch GET 200 https://registry.npmjs.org/detect-libc 781ms (cache revalidated)
84 silly fetch manifest pump@^3.0.0
85 http fetch GET 200 https://registry.npmjs.org/simple-get 824ms (cache revalidated)
86 silly fetch manifest readable-stream@^3.6.0
87 http fetch GET 200 https://registry.npmjs.org/commist 871ms (cache revalidated)
88 silly fetch manifest reinterval@^1.1.0
89 http fetch GET 200 https://registry.npmjs.org/readable-stream 51ms (cache revalidated)
90 silly fetch manifest split2@^3.1.0
91 http fetch GET 200 https://registry.npmjs.org/duplexify 807ms (cache revalidated)
92 silly fetch manifest ws@^7.5.0
93 http fetch GET 200 https://registry.npmjs.org/help-me 776ms (cache revalidated)
94 silly fetch manifest xtend@^4.0.2
95 http fetch GET 200 https://registry.npmjs.org/inherits 795ms (cache revalidated)
96 silly fetch manifest debug@^4.3.1
97 http fetch GET 200 https://registry.npmjs.org/mqtt-packet 765ms (cache revalidated)
98 http fetch GET 200 https://registry.npmjs.org/pump 775ms (cache revalidated)
99 http fetch GET 200 https://registry.npmjs.org/split2 780ms (cache revalidated)
100 http fetch GET 200 https://registry.npmjs.org/reinterval 818ms (cache revalidated)
101 http fetch GET 200 https://registry.npmjs.org/xtend 796ms (cache revalidated)
102 http fetch GET 200 https://registry.npmjs.org/ws 818ms (cache revalidated)
103 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/homebridge-camera-ffmpeg Completed in 1732ms
104 silly placeDep node_modules/homebridge-tapo-camera detect-libc@1.0.3 OK for: ffmpeg-for-homebridge@0.0.9 want: ^1.0.3
105 silly placeDep node_modules/homebridge-tapo-camera dotenv@8.6.0 OK for: ffmpeg-for-homebridge@0.0.9 want: ^8.2.0
106 silly placeDep node_modules/homebridge-tapo-camera mkdirp@1.0.4 OK for: ffmpeg-for-homebridge@0.0.9 want: ^1.0.3
107 silly placeDep node_modules/homebridge-tapo-camera simple-get@3.1.1 OK for: ffmpeg-for-homebridge@0.0.9 want: ^3.1.0
108 silly placeDep node_modules/homebridge-tapo-camera tar@6.2.0 OK for: ffmpeg-for-homebridge@0.0.9 want: ^6.0.1
109 silly fetch manifest decompress-response@^4.2.0
110 silly fetch manifest once@^1.3.1
111 silly fetch manifest simple-concat@^1.0.0
112 silly fetch manifest chownr@^2.0.0
113 silly fetch manifest fs-minipass@^2.0.0
114 silly fetch manifest minipass@^5.0.0
115 silly fetch manifest minizlib@^2.1.1
116 http fetch GET 200 https://registry.npmjs.org/minizlib 67ms (cache revalidated)
117 silly fetch manifest yallist@^4.0.0
118 http fetch GET 200 https://registry.npmjs.org/minipass 71ms (cache revalidated)
119 http fetch GET 200 https://registry.npmjs.org/once 79ms (cache revalidated)
120 http fetch GET 200 https://registry.npmjs.org/fs-minipass 80ms (cache revalidated)
121 http fetch GET 200 https://registry.npmjs.org/yallist 63ms (cache revalidated)
122 http fetch GET 200 https://registry.npmjs.org/chownr 787ms (cache revalidated)
123 http fetch GET 200 https://registry.npmjs.org/decompress-response 793ms (cache revalidated)
124 http fetch GET 200 https://registry.npmjs.org/simple-concat 837ms (cache revalidated)
125 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/ffmpeg-for-homebridge Completed in 851ms
126 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/detect-libc Completed in 0ms
127 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/dotenv Completed in 0ms
128 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/mkdirp Completed in 0ms
129 silly fetch manifest bufferutil@^4.0.1
130 http fetch GET 200 https://registry.npmjs.org/bufferutil 60ms (cache revalidated)
131 silly fetch manifest utf-8-validate@^5.0.2
132 http fetch GET 200 https://registry.npmjs.org/utf-8-validate 45ms (cache revalidated)
133 silly placeDep node_modules/homebridge-tapo-camera commist@1.1.0 OK for: mqtt@4.2.8 want: ^1.0.0
134 silly placeDep node_modules/homebridge-tapo-camera concat-stream@2.0.0 OK for: mqtt@4.2.8 want: ^2.0.0
135 silly placeDep node_modules/homebridge-tapo-camera debug@4.3.4 OK for: mqtt@4.2.8 want: ^4.1.1
136 silly placeDep node_modules/homebridge-tapo-camera duplexify@4.1.2 OK for: mqtt@4.2.8 want: ^4.1.1
137 silly placeDep node_modules/homebridge-tapo-camera help-me@3.0.0 OK for: mqtt@4.2.8 want: ^3.0.0
138 silly placeDep node_modules/homebridge-tapo-camera inherits@2.0.4 OK for: mqtt@4.2.8 want: ^2.0.3
139 silly placeDep node_modules/homebridge-tapo-camera minimist@1.2.8 OK for: mqtt@4.2.8 want: ^1.2.5
140 silly placeDep node_modules/homebridge-tapo-camera mqtt-packet@6.10.0 OK for: mqtt@4.2.8 want: ^6.8.0
141 silly placeDep node_modules/homebridge-tapo-camera pump@3.0.0 OK for: mqtt@4.2.8 want: ^3.0.0
142 silly placeDep node_modules/homebridge-tapo-camera readable-stream@3.6.2 OK for: mqtt@4.2.8 want: ^3.6.0
143 silly placeDep node_modules/homebridge-tapo-camera reinterval@1.1.0 OK for: mqtt@4.2.8 want: ^1.1.0
144 silly placeDep node_modules/homebridge-tapo-camera split2@3.2.2 OK for: mqtt@4.2.8 want: ^3.1.0
145 silly placeDep node_modules/homebridge-tapo-camera ws@7.5.9 OK for: mqtt@4.2.8 want: ^7.5.0
146 silly placeDep node_modules/homebridge-tapo-camera xtend@4.0.2 OK for: mqtt@4.2.8 want: ^4.0.2
147 silly fetch manifest leven@^2.1.0
148 silly fetch manifest minimist@^1.1.0
149 silly fetch manifest buffer-from@^1.0.0
150 silly fetch manifest readable-stream@^3.0.2
151 silly fetch manifest typedarray@^0.0.6
152 silly fetch manifest ms@2.1.2
153 silly fetch manifest end-of-stream@^1.4.1
154 silly fetch manifest readable-stream@^3.1.1
155 silly fetch manifest stream-shift@^1.0.0
156 silly fetch manifest glob@^7.1.6
157 http fetch GET 200 https://registry.npmjs.org/leven 65ms (cache revalidated)
158 silly fetch manifest bl@^4.0.2
159 http fetch GET 200 https://registry.npmjs.org/ms 66ms (cache revalidated)
160 silly fetch manifest process-nextick-args@^2.0.1
161 http fetch GET 200 https://registry.npmjs.org/buffer-from 80ms (cache revalidated)
162 silly fetch manifest end-of-stream@^1.1.0
163 http fetch GET 200 https://registry.npmjs.org/glob 79ms (cache revalidated)
164 silly fetch manifest string_decoder@^1.1.1
165 http fetch GET 200 https://registry.npmjs.org/end-of-stream 90ms (cache revalidated)
166 silly fetch manifest util-deprecate@^1.0.1
167 http fetch GET 200 https://registry.npmjs.org/typedarray 98ms (cache revalidated)
168 http fetch GET 200 https://registry.npmjs.org/process-nextick-args 59ms (cache revalidated)
169 http fetch GET 200 https://registry.npmjs.org/bl 73ms (cache revalidated)
170 http fetch GET 200 https://registry.npmjs.org/end-of-stream 66ms (cache revalidated)
171 http fetch GET 200 https://registry.npmjs.org/string_decoder 60ms (cache revalidated)
172 http fetch GET 200 https://registry.npmjs.org/util-deprecate 64ms (cache revalidated)
173 http fetch GET 200 https://registry.npmjs.org/stream-shift 806ms (cache revalidated)
174 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/mqtt Completed in 949ms
175 silly placeDep node_modules/homebridge-tapo-camera leven@2.1.0 OK for: commist@1.1.0 want: ^2.1.0
176 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/commist Completed in 1ms
177 silly placeDep node_modules/homebridge-tapo-camera buffer-from@1.1.2 OK for: concat-stream@2.0.0 want: ^1.0.0
178 silly placeDep node_modules/homebridge-tapo-camera typedarray@0.0.6 OK for: concat-stream@2.0.0 want: ^0.0.6
179 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/concat-stream Completed in 3ms
180 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/buffer-from Completed in 0ms
181 silly placeDep node_modules/homebridge-tapo-camera ms@2.1.2 OK for: debug@4.3.4 want: 2.1.2
182 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/debug Completed in 2ms
183 silly placeDep node_modules/homebridge-tapo-camera end-of-stream@1.4.4 OK for: duplexify@4.1.2 want: ^1.4.1
184 silly placeDep node_modules/homebridge-tapo-camera stream-shift@1.0.3 OK for: duplexify@4.1.2 want: ^1.0.0
185 silly fetch manifest once@^1.4.0
186 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/duplexify Completed in 2ms
187 silly placeDep node_modules/homebridge-tapo-camera once@1.4.0 OK for: end-of-stream@1.4.4 want: ^1.4.0
188 silly fetch manifest wrappy@1
189 http fetch GET 200 https://registry.npmjs.org/wrappy 60ms (cache revalidated)
190 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/end-of-stream Completed in 64ms
191 silly placeDep node_modules/homebridge-tapo-camera glob@7.2.3 OK for: help-me@3.0.0 want: ^7.1.6
192 silly fetch manifest fs.realpath@^1.0.0
193 silly fetch manifest inflight@^1.0.4
194 silly fetch manifest minimatch@^3.1.1
195 silly fetch manifest path-is-absolute@^1.0.0
196 http fetch GET 200 https://registry.npmjs.org/inflight 67ms (cache revalidated)
197 http fetch GET 200 https://registry.npmjs.org/minimatch 73ms (cache revalidated)
198 http fetch GET 200 https://registry.npmjs.org/path-is-absolute 250ms (cache revalidated)
199 http fetch GET 200 https://registry.npmjs.org/fs.realpath 802ms (cache revalidated)
200 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/help-me Completed in 806ms
201 silly placeDep node_modules/homebridge-tapo-camera fs.realpath@1.0.0 OK for: glob@7.2.3 want: ^1.0.0
202 silly placeDep node_modules/homebridge-tapo-camera inflight@1.0.6 OK for: glob@7.2.3 want: ^1.0.4
203 silly placeDep node_modules/homebridge-tapo-camera minimatch@3.1.2 OK for: glob@7.2.3 want: ^3.1.1
204 silly placeDep node_modules/homebridge-tapo-camera path-is-absolute@1.0.1 OK for: glob@7.2.3 want: ^1.0.0
205 silly fetch manifest brace-expansion@^1.1.7
206 http fetch GET 200 https://registry.npmjs.org/brace-expansion 57ms (cache revalidated)
207 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/glob Completed in 64ms
208 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/fs.realpath Completed in 0ms
209 silly placeDep node_modules/homebridge-tapo-camera wrappy@1.0.2 OK for: inflight@1.0.6 want: 1
210 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/inflight Completed in 1ms
211 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/inherits Completed in 0ms
212 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/leven Completed in 0ms
213 silly placeDep node_modules/homebridge-tapo-camera brace-expansion@1.1.11 OK for: minimatch@3.1.2 want: ^1.1.7
214 silly fetch manifest balanced-match@^1.0.0
215 silly fetch manifest concat-map@0.0.1
216 http fetch GET 200 https://registry.npmjs.org/balanced-match 97ms (cache revalidated)
217 http fetch GET 200 https://registry.npmjs.org/concat-map 788ms (cache revalidated)
218 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/minimatch Completed in 791ms
219 silly placeDep node_modules/homebridge-tapo-camera balanced-match@1.0.2 OK for: brace-expansion@1.1.11 want: ^1.0.0
220 silly placeDep node_modules/homebridge-tapo-camera concat-map@0.0.1 OK for: brace-expansion@1.1.11 want: 0.0.1
221 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/brace-expansion Completed in 4ms
222 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/balanced-match Completed in 0ms
223 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/concat-map Completed in 0ms
224 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/minimist Completed in 0ms
225 silly placeDep node_modules/homebridge-tapo-camera bl@4.1.0 OK for: mqtt-packet@6.10.0 want: ^4.0.2
226 silly placeDep node_modules/homebridge-tapo-camera process-nextick-args@2.0.1 OK for: mqtt-packet@6.10.0 want: ^2.0.1
227 silly fetch manifest buffer@^5.5.0
228 http fetch GET 200 https://registry.npmjs.org/buffer 816ms (cache revalidated)
229 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/mqtt-packet Completed in 828ms
230 silly placeDep node_modules/homebridge-tapo-camera buffer@5.7.1 OK for: bl@4.1.0 want: ^5.5.0
231 silly fetch manifest base64-js@^1.3.1
232 silly fetch manifest ieee754@^1.1.13
233 http fetch GET 200 https://registry.npmjs.org/base64-js 55ms (cache revalidated)
234 http fetch GET 200 https://registry.npmjs.org/ieee754 56ms (cache revalidated)
235 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/bl Completed in 62ms
236 silly placeDep node_modules/homebridge-tapo-camera base64-js@1.5.1 OK for: buffer@5.7.1 want: ^1.3.1
237 silly placeDep node_modules/homebridge-tapo-camera ieee754@1.2.1 OK for: buffer@5.7.1 want: ^1.1.13
238 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/buffer Completed in 3ms
239 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/base64-js Completed in 0ms
240 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/ieee754 Completed in 0ms
241 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/ms Completed in 0ms
242 silly placeDep node_modules/homebridge-tapo-camera whatwg-url@5.0.0 OK for: node-fetch@2.7.0 want: ^5.0.0
243 silly fetch manifest tr46@~0.0.3
244 silly fetch manifest webidl-conversions@^3.0.0
245 http fetch GET 200 https://registry.npmjs.org/tr46 779ms (cache revalidated)
246 http fetch GET 200 https://registry.npmjs.org/webidl-conversions 797ms (cache revalidated)
247 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/node-fetch Completed in 801ms
248 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/once Completed in 0ms
249 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/onvif Completed in 0ms
250 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/path-is-absolute Completed in 0ms
251 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/pick-port Completed in 0ms
252 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/process-nextick-args Completed in 0ms
253 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/pump Completed in 0ms
254 silly placeDep node_modules/homebridge-tapo-camera string_decoder@1.3.0 OK for: readable-stream@3.6.2 want: ^1.1.1
255 silly placeDep node_modules/homebridge-tapo-camera util-deprecate@1.0.2 OK for: readable-stream@3.6.2 want: ^1.0.1
256 silly fetch manifest safe-buffer@~5.2.0
257 http fetch GET 200 https://registry.npmjs.org/safe-buffer 55ms (cache revalidated)
258 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/readable-stream Completed in 60ms
259 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/reinterval Completed in 0ms
260 silly placeDep node_modules/homebridge-tapo-camera decompress-response@4.2.1 OK for: simple-get@3.1.1 want: ^4.2.0
261 silly placeDep node_modules/homebridge-tapo-camera simple-concat@1.0.1 OK for: simple-get@3.1.1 want: ^1.0.0
262 silly fetch manifest mimic-response@^2.0.0
263 http fetch GET 200 https://registry.npmjs.org/mimic-response 764ms (cache revalidated)
264 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/simple-get Completed in 769ms
265 silly placeDep node_modules/homebridge-tapo-camera mimic-response@2.1.0 OK for: decompress-response@4.2.1 want: ^2.0.0
266 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/decompress-response Completed in 2ms
267 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/mimic-response Completed in 0ms
268 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/simple-concat Completed in 0ms
269 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/split2 Completed in 0ms
270 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/stream-shift Completed in 0ms
271 silly placeDep node_modules/homebridge-tapo-camera safe-buffer@5.2.1 OK for: string_decoder@1.3.0 want: ~5.2.0
272 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/string_decoder Completed in 1ms
273 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/safe-buffer Completed in 0ms
274 silly placeDep node_modules/homebridge-tapo-camera chownr@2.0.0 OK for: tar@6.2.0 want: ^2.0.0
275 silly placeDep node_modules/homebridge-tapo-camera fs-minipass@2.1.0 OK for: tar@6.2.0 want: ^2.0.0
276 silly placeDep node_modules/homebridge-tapo-camera minipass@5.0.0 OK for: tar@6.2.0 want: ^5.0.0
277 silly placeDep node_modules/homebridge-tapo-camera minizlib@2.1.2 OK for: tar@6.2.0 want: ^2.1.1
278 silly placeDep node_modules/homebridge-tapo-camera yallist@4.0.0 OK for: tar@6.2.0 want: ^4.0.0
279 silly fetch manifest minipass@^3.0.0
280 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/tar Completed in 9ms
281 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/chownr Completed in 0ms
282 silly placeDep node_modules/homebridge-tapo-camera/node_modules/fs-minipass minipass@3.3.6 OK for: fs-minipass@2.1.0 want: ^3.0.0
283 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/fs-minipass Completed in 2ms
284 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/minipass Completed in 0ms
285 silly placeDep node_modules/homebridge-tapo-camera/node_modules/minizlib minipass@3.3.6 OK for: minizlib@2.1.2 want: ^3.0.0
286 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/minizlib Completed in 2ms
287 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/typedarray Completed in 0ms
288 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/util-deprecate Completed in 0ms
289 silly placeDep node_modules/homebridge-tapo-camera tr46@0.0.3 OK for: whatwg-url@5.0.0 want: ~0.0.3
290 silly placeDep node_modules/homebridge-tapo-camera webidl-conversions@3.0.1 OK for: whatwg-url@5.0.0 want: ^3.0.0
291 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/whatwg-url Completed in 2ms
292 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/tr46 Completed in 0ms
293 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/webidl-conversions Completed in 0ms
294 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/wrappy Completed in 0ms
295 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/ws Completed in 0ms
296 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/xtend Completed in 0ms
297 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/yallist Completed in 0ms
298 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/fs-minipass/node_modules/minipass Completed in 0ms
299 timing idealTree:node_modules/homebridge-tapo-camera/node_modules/minizlib/node_modules/minipass Completed in 0ms
300 timing idealTree:buildDeps Completed in 10604ms
301 timing idealTree:fixDepFlags Completed in 1ms
302 timing idealTree Completed in 10617ms
303 timing command:install Completed in 10630ms
304 verbose stack Error: An unknown git error occurred
304 verbose stack     at makeError (C:\Users\vince\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\make-error.js:28:13)
304 verbose stack     at C:\Users\vince\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\git\lib\spawn.js:37:26
304 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
305 verbose cwd C:\Users\vince\AppData\Roaming\npm
306 verbose Windows_NT 10.0.22000
307 verbose node v20.11.0
308 verbose npm  v10.4.0
309 error code ENOENT
310 error syscall spawn git
311 error path git
312 error errno -4058
313 error enoent An unknown git error occurred
314 error enoent This is related to npm not being able to find a file.
314 error enoent
315 verbose exit -4058
316 timing npm Completed in 11111ms
317 verbose unfinished npm timer reify 1706469175927
318 verbose unfinished npm timer reify:loadTrees 1706469175934
319 verbose code -4058
320 error A complete log of this run can be found in: C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2024-01-28T19_12_55_449Z-debug-0.log



**Environment:**

* **Plugin Version**: v2.3.4
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.11.0
* **NPM Version**: 10.4.0
* **Operating System**: Microsoft Windows 11 Famille (10.0.22000)

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by r4z8rt** [comment]
GIT needs to be installed to work

**Comment by r4z8rt** [comment]
GIT needs to be installed to work
