### ISSUE TITLE
Error Code - Invalid Device Confirm

### ISSUE THREAD

**Issue by mecoreyg** [kopiro/homebridge-tapo-camera#140]
**Describe Your Problem:**
In HB, get red error code even though sometimes the camera work inside of Apple Home.
**Logs:**

```
Error at 'getStatusAndUpdateCharacteristics'. Error: Invalid device confirm
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:205:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:335:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:415:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)
```

**Environment:**

* **Plugin Version**: 2.3.4
* **Homebridge Version**: 1.8.3
* **Node.js Version**: 20.15.1
* **NPM Version**: 
* **Operating System**: MacOS

**Comment by kopiro** [comment]
Same as https://github.com/kopiro/homebridge-tapo-camera/issues/132
