### ISSUE TITLE
Can't add C225 to Homebridge

### ISSUE THREAD

**Issue by slavisaurus** [kopiro/homebridge-tapo-camera#147]
**Describe Your Problem:**
I'm unable to add my Tapo C225 to the plugin. I previously haven't connected it.

When the device and service is on, I consistently get the "Invalid device" error. 

I've checked that: 
- IP is correct
- RTSP is enabled 
- tried different variations of user/no user name for Tapo username/password 
- there aren't any special characters in the user name or password for the RTSP feed

I'm mostly just trying to get the Privacy Switch enabled so I can add an automation. 

**Logs:**

```
[7/23/2024, 4:59:59 PM] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Invalid device confirm
    at TAPOCamera.refreshStok (/volume1/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:205:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/volume1/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:335:19)
    at /volume1/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:415:23
    at TAPOCamera.getStatus (/volume1/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:555:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/volume1/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/volume1/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)
```

**Plugin Config:**

```json
 "cameras": [
                {
                    "name": "Tapo Homekit",
                    "ipAddress": "192.168.7.250",
                    "password": "passXXXXXXXX",
                    "streamUser": "userXXXXXXXX",
                    "streamPassword": "passXXXXXXX",
                    "debug": true,
                    "disableStreaming": true,
                    "disableAlarmAccessory": true,
                    "disableMotionAccessory": true,
                    "privacyAccessoryName": "Tapo Privacy",
                    "alarmAccessoryName": "Tapo Alarm"
```
**Environment:**

* **Plugin Version**: 2.3.4
* **Homebridge Version**:v.1.8.4
* **Node.js Version**: v18.18.2
* **NPM Version**: 
* **Operating System**: Synology DSM

**Comment by slavisaurus** [comment]
Update:

Switched over to a Raspberry Pi with NodeJS v20.12.2 and I’m still experiencing the same issue.

**Comment by Suzuhana** [comment]
I am experiencing the same:

```
[8/7/2024, 1:05:12 AM] [Tapo Garage Cam] Error when retrieving data Error: Invalid device confirm
    at TAPOCamera.refreshStok (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:213:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:349:19)
    at /homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:205:28)
```

**Comment by Suzuhana** [comment]
I just figured out. Try to scroll to the top of error logs, there should be something like:

[8/7/2024, 1:15:30 AM] Please add [Tapo Garage Cam 86C9] manually in Home app. Setup Code: xxx-xx-xxx

Add the camera manually in homekit. However, accessories of the camera are not working.

**Comment by kopiro** [comment]
Same issue as https://github.com/kopiro/homebridge-tapo-camera/issues/132
