### ISSUE TITLE
Homebridge does not start up correctly after update

### ISSUE THREAD

**Issue by tomberriman** [kopiro/homebridge-tapo-camera#157]
**Describe The Bug:**

**To Reproduce:**

**Expected behavior:**

**Logs:**
[8/9/2024, 11:49:32 AM] Got SIGTERM, shutting down Homebridge...
[8/9/2024, 11:49:32 AM] Error: Invalid authentication data
```
Show the Homebridge logs here, remove any sensitive information.
```ror when retrieving data Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:349:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:205:28)
[8/9/2024, 7:49:21 AM] [Spare Room Camera] Error when retrieving data Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:349:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:205:28)

Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 523-08-538 │     
    └────────────┘     
                       
[8/9/2024, 11:09:19 AM] Homebridge v1.8.4 (HAP v0.12.2) (Homebridge AE9D) is running on port 51375.
[8/9/2024, 11:09:19 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/9/2024, 11:09:19 AM] Stairs Camera 32A5 is running on port 57745.
[8/9/2024, 11:09:19 AM] Please add [Stairs Camera 32A5] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:19 AM] Spare Room Camera BC3B is running on port 57754.
[8/9/2024, 11:09:19 AM] Please add [Spare Room Camera BC3B] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:20 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
[8/9/2024, 11:09:20 AM] Living Room Camera 641D is running on port 57758.
[8/9/2024, 11:09:20 AM] Please add [Living Room Camera 641D] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:20 AM] Got SIGTERM, shutting down Homebridge...
[8/9/2024, 11:09:20 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
[8/9/2024, 11:09:21 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
[8/9/2024, 11:09:23 AM] [Homebridge UI] Homebridge restart request received
[8/9/2024, 11:09:23 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[8/9/2024, 11:09:23 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[8/9/2024, 11:09:25 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/9/2024, 11:09:30 AM] [HB Supervisor] Restarting Homebridge...
[8/9/2024, 11:09:30 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[8/9/2024, 11:09:30 AM] [HB Supervisor] Started Homebridge v1.8.4 with PID: 23654
[8/9/2024, 11:09:30 AM] Loaded config.json with 0 accessories and 4 platforms.
[8/9/2024, 11:09:30 AM] Loaded 10 cached accessories from cachedAccessories.
[8/9/2024, 11:09:30 AM] ---
[8/9/2024, 11:09:30 AM] Loaded plugin: homebridge-config-ui-x@4.56.4
[8/9/2024, 11:09:30 AM] Registering platform 'homebridge-config-ui-x.config'
[8/9/2024, 11:09:30 AM] ---
[8/9/2024, 11:09:30 AM] Loaded plugin: homebridge-nest@4.6.9
[8/9/2024, 11:09:30 AM] Registering platform 'homebridge-nest.Nest'
[8/9/2024, 11:09:30 AM] ---
[8/9/2024, 11:09:30 AM] Loaded plugin: homebridge-tapo-camera@2.4.3
[8/9/2024, 11:09:30 AM] Registering platform 'homebridge-tapo-camera.tapo-camera'
[8/9/2024, 11:09:30 AM] ---
[8/9/2024, 11:09:30 AM] Loaded plugin: homebridge-tplink-smarthome@8.0.3
[8/9/2024, 11:09:30 AM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[8/9/2024, 11:09:30 AM] ---

Setup Payload:
X-HM://0024C2PMI9FUK
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 523-08-538 │     
    └────────────┘     
                       
[8/9/2024, 11:09:30 AM] Homebridge v1.8.4 (HAP v0.12.2) (Homebridge AE9D) is running on port 51375.
[8/9/2024, 11:09:30 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0


[8/9/2024, 11:09:31 AM] Stairs Camera 32A5 is running on port 57792.
[8/9/2024, 11:09:31 AM] Please add [Stairs Camera 32A5] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:31 AM] Living Room Camera 641D is running on port 57795.
[8/9/2024, 11:09:31 AM] Please add [Living Room Camera 641D] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:31 AM] Spare Room Camera BC3B is running on port 57799.
[8/9/2024, 11:09:31 AM] Please add [Spare Room Camera BC3B] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:31 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
[8/9/2024, 11:09:31 AM] Got SIGTERM, shutting down Homebridge...
[8/9/2024, 11:09:32 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
[8/9/2024, 11:09:32 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
[8/9/2024, 11:09:36 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/9/2024, 11:09:41 AM] [HB Supervisor] Restarting Homebridge...
[8/9/2024, 11:09:41 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[8/9/2024, 11:09:41 AM] [HB Supervisor] Started Homebridge v1.8.4 with PID: 23752
[8/9/2024, 11:09:41 AM] Loaded config.json with 0 accessories and 4 platforms.
[8/9/2024, 11:09:41 AM] Loaded 10 cached accessories from cachedAccessories.
[8/9/2024, 11:09:41 AM] ---
[8/9/2024, 11:09:41 AM] Loaded plugin: homebridge-config-ui-x@4.56.4
[8/9/2024, 11:09:41 AM] Registering platform 'homebridge-config-ui-x.config'
[8/9/2024, 11:09:41 AM] ---
[8/9/2024, 11:09:41 AM] Loaded plugin: homebridge-nest@4.6.9
[8/9/2024, 11:09:41 AM] Registering platform 'homebridge-nest.Nest'
[8/9/2024, 11:09:41 AM] ---
[8/9/2024, 11:09:42 AM] Loaded plugin: homebridge-tapo-camera@2.4.3
[8/9/2024, 11:09:42 AM] Registering platform 'homebridge-tapo-camera.tapo-camera'
[8/9/2024, 11:09:42 AM] ---
[8/9/2024, 11:09:42 AM] Loaded plugin: homebridge-tplink-smarthome@8.0.3
[8/9/2024, 11:09:42 AM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[8/9/2024, 11:09:42 AM] ---
[8/9/2024, 11:09:42 AM] Loading 4 platforms...
[8/9/2024, 11:09:42 AM] [Nest] Initializing Nest platform...
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] homebridge-tplink-smarthome v8.0.3, node v20.16.0, homebridge v1.8.4, api v2.7
[8/9/2024, 11:09:42 AM] [tapo-camera] Initializing tapo-camera platform...
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Configuring cached accessory: [Dyson] UUID: bf226e90-76dd-452f-b8bf-c7c4f92a8bd6 deviceId: 8006C9533A897ADCDC819DB7B888632820F9BA4B 
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Configuring cached accessory: [Living Room Air Filter] UUID: e263c803-7d74-42b4-8213-bb2546474c2d deviceId: 8006B39F2FDB368516F1D175167ED5701B3A3C65 
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Configuring cached accessory: [Niketa’s Light] UUID: b7862fe5-ee54-4d6e-bf2f-cc7c0ecf9776 deviceId: 80064F4637AF5612FC55DF1C739B8B421D6ACB9B 
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Configuring cached accessory: [Corner Light] UUID: b808e32d-f655-46a8-8735-c78bfe92d85d deviceId: 80069E01BD487F87E50BCF6E337156EA186A8D50 
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Configuring cached accessory: [Bedroom Side Light] UUID: fe1006e4-4a52-4407-a459-582fcbcc335b deviceId: 80120481F9C66FC7186721269B7DB5C518AF6FE9 
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Configuring cached accessory: [Spare Room] UUID: 577de0cc-9193-4365-a8c4-634bdb4539ba deviceId: 8006102B5A0A2EA562585AE5C77FB19118368E27 
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Configuring cached accessory: [Bedroom Air Filter] UUID: 2bd72f47-c558-481c-ac00-460e186ed7ed deviceId: 800619A3B9C009CCA424BB5BE13A390318D4A147 
[8/9/2024, 11:09:42 AM] [Nest] Fetching Nest devices.
Setup Payload:
X-HM://0024C2PMI9FUK
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 523-08-538 │     
    └────────────┘     
                       
[8/9/2024, 11:09:42 AM] Homebridge v1.8.4 (HAP v0.12.2) (Homebridge AE9D) is running on port 51375.
[8/9/2024, 11:09:42 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Device First Online: [Corner Light] plug [80069E01BD487F87E50BCF6E337156EA186A8D50] 192.168.68.71 9999
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Adding: [Corner Light] plug [80069E01BD487F87E50BCF6E337156EA186A8D50]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] [Corner Light] Removing stale Characteristic: [Outlet.Brightness] uuid:[00000008-0000-1000-8000-0026BB765291]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Device First Online: [Shark] plug [800619A3B9C009CCA424BB5BE13A390318D4A147] 192.168.68.72 9999
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Adding: [Shark] plug [800619A3B9C009CCA424BB5BE13A390318D4A147]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] [Shark] Removing stale Characteristic: [Outlet.Brightness] uuid:[00000008-0000-1000-8000-0026BB765291]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Device First Online: [Gym] plug [8006102B5A0A2EA562585AE5C77FB19118368E27] 192.168.68.67 9999
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Adding: [Gym] plug [8006102B5A0A2EA562585AE5C77FB19118368E27]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] [Gym] Removing stale Characteristic: [Outlet.Brightness] uuid:[00000008-0000-1000-8000-0026BB765291]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Device First Online: [Macbook Air] plug [8006C9533A897ADCDC819DB7B888632820F9BA4B] 192.168.68.50 9999
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Adding: [Macbook Air] plug [8006C9533A897ADCDC819DB7B888632820F9BA4B]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] [Macbook Air] Removing stale Characteristic: [Outlet.Brightness] uuid:[00000008-0000-1000-8000-0026BB765291]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Device First Online: [Niketa’s Light] plug [80064F4637AF5612FC55DF1C739B8B421D6ACB9B] 192.168.68.52 9999
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Adding: [Niketa’s Light] plug [80064F4637AF5612FC55DF1C739B8B421D6ACB9B]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] [Niketa’s Light] Removing stale Characteristic: [Outlet.Brightness] uuid:[00000008-0000-1000-8000-0026BB765291]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Device First Online: [Bedroom ] plug [8006B39F2FDB368516F1D175167ED5701B3A3C65] 192.168.68.65 9999
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] Adding: [Bedroom ] plug [8006B39F2FDB368516F1D175167ED5701B3A3C65]
[8/9/2024, 11:09:42 AM] [TplinkSmarthome] [Bedroom ] Removing stale Characteristic: [Outlet.Brightness] uuid:[00000008-0000-1000-8000-0026BB765291]
[8/9/2024, 11:09:42 AM] Stairs Camera 32A5 is running on port 57829.
[8/9/2024, 11:09:42 AM] Please add [Stairs Camera 32A5] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:42 AM] Living Room Camera 641D is running on port 57835.
[8/9/2024, 11:09:42 AM] Please add [Living Room Camera 641D] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:42 AM] Spare Room Camera BC3B is running on port 57840.
[8/9/2024, 11:09:42 AM] Please add [Spare Room Camera BC3B] manually in Home app. Setup Code: 523-08-538
[8/9/2024, 11:09:42 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
[8/9/2024, 11:09:42 AM] Got SIGTERM, shutting down Homebridge...
[8/9/2024, 11:09:42 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
[8/9/2024, 11:09:43 AM] Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:340:7)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:348:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
    at TAPOCamera.getStatus (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:612:26)
    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:204:26)
/var/folders/2s/yy6bz1356m360tpxydvq352w0000gn/T/homebridge-backup-HOo6qE
[8/9/2024, 11:09:45 AM] [Homebridge UI] Starting backup restore...
[8/9/2024, 11:09:47 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[8/9/2024, 11:09:47 AM] [Homebridge UI] Running Command: npm install -g homebridge-tapo-camera@2.4.1
[8/9/2024, 11:09:50 AM] [Homebridge UI] Running Command: npm install -g homebridge-tplink-smarthome@8.0.3
[8/9/2024, 11:09:52 AM] [HB Supervisor] Restarting Homebridge...
[8/9/2024, 11:09:52 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[8/9/2024, 11:09:52 AM] [HB Supervisor] Started Homebridge v1.8.4 with PID: 23837
[8/9/2024, 11:09:52 AM] Loaded config.json with 0 accessories and 4 platforms.
[8/9/2024, 11:09:52 AM] Loaded 10 cached accessories from cachedAccessories.
[8/9/2024, 11:09:52 AM] ---
[8/9/2024, 11:09:52 AM] Plugin /usr/local/lib/node_modules/homebridge-tplink-smarthome does not contain a package.json.
[8/9/2024, 11:09:52 AM] Loaded plugin: homebridge-config-ui-x@4.56.4
[8/9/2024, 11:09:52 AM] Registering platform 'homebridge-config-ui-x.config'
[8/9/2024, 11:09:52 AM] ---
[8/9/2024, 11:09:53 AM] Loaded plugin: homebridge-nest@4.6.9
[8/9/2024, 11:09:53 AM] Registering platform 'homebridge-nest.Nest'
[8/9/2024, 11:09:53 AM] ---
[8/9/2024, 11:09:53 AM] Loaded plugin: homebridge-tapo-camera@2.4.1
[8/9/2024, 11:09:53 AM] Registering platform 'homebridge-tapo-camera.tapo-camera'
[8/9/2024, 11:09:53 AM] ---
[8/9/2024, 11:09:53 AM] Loading 4 platforms...
[8/9/2024, 11:09:53 AM] [Nest] Initializing Nest platform...
[8/9/2024, 11:09:53 AM] No plugin was found for the platform "TplinkSmarthome" in your config.json. Please make sure the corresponding plugin is installed correctly.
[8/9/2024, 11:09:53 AM] [tapo-camera] Initializing tapo-camera platform...
[8/9/2024, 11:09:53 AM] Failed to find plugin to handle accessory Dyson
[8/9/2024, 11:09:53 AM] Removing orphaned accessory Dyson
[8/9/2024, 11:09:53 AM] Failed to find plugin to handle accessory Living Room Air Filter
[8/9/2024, 11:09:53 AM] Removing orphaned accessory Living Room Air Filter
[8/9/2024, 11:09:53 AM] Failed to find plugin to handle accessory Niketa’s Light
[8/9/2024, 11:09:53 AM] Removing orphaned accessory Niketa’s Light
[8/9/2024, 11:09:53 AM] Failed to find plugin to handle accessory Corner Light
[8/9/2024, 11:09:53 AM] Removing orphaned accessory Corner Light
[8/9/2024, 11:09:53 AM] Failed to find plugin to handle accessory Bedroom Side Light
[8/9/2024, 11:09:53 AM] Removing orphaned accessory Bedroom Side Light
[8/9/2024, 11:09:53 AM] Failed to find plugin to handle accessory Spare Room
[8/9/2024, 11:09:53 AM] Removing orphaned accessory Spare Room
[8/9/2024, 11:09:53 AM] Failed to find plugin to handle accessory Bedroom Air Filter
[8/9/2024, 11:09:53 AM] Removing orphaned accessory Bedroom Air Filter
[8/9/2024, 11:09:53 AM] [Nest] Fetching Nest devices.
Setup Payload:
X-HM://0024C2PMI9FUK
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 523-08-538 │     
    └────────────┘     
                       

    at CameraAccessory.getStatusAndNotify (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:205:28)
[8/9/2024, 11:10:03 AM] [Spare Room Camera] Error when retrieving data Error: Invalid authentication data
    at TAPOCamera.refreshStok (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:299:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:349:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:429:23
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:03 AM] [homebridge-tapo-camera] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Invalid authentication data. See https://homebridge.io/w/JtMGR for more info.
[8/9/2024, 11:10:09 AM] [Nest] initing thermostat "Kitchen Thermostat": deviceId: 09AB01AC072100UE structureId: 083623c1-17d9-11eb-b3cb-1264be8c71b4
[Kitchen Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 9
[8/9/2024, 11:10:09 AM] [Nest] initing thermostat "Bedroom Thermostat": deviceId: 09AB01AC3420008T structureId: 083623c1-17d9-11eb-b3cb-1264be8c71b4
[Bedroom Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 9
[8/9/2024, 11:10:09 AM] [Nest] initing home_away_sensor "Home Occupied": deviceId: 083623c1-17d9-11eb-b3cb-1264be8c71b4 structureId: 083623c1-17d9-11eb-b3cb-1264be8c71b4



**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```{
    "cameras": [
        {
            "name": "Living Room Camera",
            "ipAddress": “xxx”xxx,
            "username": “xxxxxxx”,
            "password": “xxxxxx”,
            "streamUser": “xxxx”,
            "streamPassword": “xxxxxx”,
            "disableEyesToggleAccessory": true
        },
        {
            "name": "Stairs Camera",
            "ipAddress": “xxxxx”,
            "username": “xxxxxx”,
            "password": “xxxxxx”,
            "streamUser": “xxxxxx”,
            "streamPassword": “xxxxxxxx”,
            "disableEyesToggleAccessory": true
        },
        {
            "name": "Spare Room Camera",
            "ipAddress": “xxxxxx”,
            "username": “xxxxx”,
            "password": “xxxxxx”,
            "streamUser": “xxxxxx”,
            "streamPassword": “xxxxxx”,
            "disableEyesToggleAccessory": true
        }
    ],
    "platform": "tapo-camera"
}

**Screenshots:**
<!-- If applicable, add screenshots to help explain your problem. -->

**Environment:**
mac os 14.6.1
* **Plugin Version**:
* **Homebridge Version**: <!-- homebridge -V Installed: v1.8.4 -->
* **Node.js Version**: <!-- node -v v20.16.0 -->
* **NPM Version**: <!-- npm -v 10.8.1 -->
* **Operating System**: <!-- macOS  - hb-service -->

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by tomberriman** [comment]
resolved after re-adding all cameras with no tapo username and upgrading to newest version, thanks for continuously supporting and updating this app
