### ISSUE TITLE
No plugin was founded 

### ISSUE THREAD

**Issue by cicciovo** [kopiro/homebridge-tapo-camera#17]
Hi, why in the log of homebridge i obtain this:? no plugin was found for the platform tapo-camera in your config.json.
I have installed the plugin and my config.json is: 
{
            "platform": "TAPO-CAMERA",
            "cameras": [
                {
                    "name": "camera",
                    "ipAddress": "192.168.1.10",
                    "password": "xxxxxx",
                    "streamPassword": "xxxxx",
                    "streamUser": "xxxxxx",
                    "pullInterval": 60000,
                    "debug": true,
                    "disableStreaming": false,
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false,
                    "lowQuality": false
                }
            ]
        },
        Any idea?

**Comment by kopiro** [comment]
Do you have the this config under `platforms` ?

```json5
{
  "bridge": { ... },
  "accessories": { ... },
  "platforms": [
      // here
  ]
}
```

**Comment by cicciovo** [comment]
Yes, i have this. 
In italiano forse ci capiamo meglio 😅 
Altre piattaforme mi vengono riconosciute e caricate. La tua mi dice che manca il plugin nonostante l’abbia scaricato prima via interfaccia grafica, poi disinstallato e installato via terminale.

**Comment by kopiro** [comment]
Can you send the log and the full structure of the config? (remove all the personal data of course)

**Comment by cicciovo** [comment]
Sure!
{
    "bridge": {
        "name": "Homebridge",
        "username": "FB:12:3A:A4:AD:10",
        "port": 33441,
        "pin": "031-45-154"
    },
    "accessories": [
        {
            "accessory": "SamsungAirconditioner",
            "name": "Climatizzatore",
            "ip": "192.168.1.17",
            "token": "xxxxx",
            "patchCert": "xxxxx"
        },
        {
            "accessory": "SamsungPowerConsumption",
            "name": "CorrenteTot",
            "ip": "192.168.1.17",
            "token": "xxxxx",
            "patchCert": "xxxxx",
            "patchDatabase": "/home/pi/webcam/",
            "dataBName": "datab"
        },
        {
            "accessory": "SamsungPowerConsumption",
            "name": "CorrenteTotCucina",
            "ip": "192.168.1.18",
            "token": "xxxxx",
            "patchCert": "xxxxx",
            "patchDatabase": "/home/pi/webcam/",
            "dataBName": "databCucina"
        },
        {
            "accessory": "SamsungAirconditioner",
            "name": "Climatizzatore2",
            "ip": "192.168.1.14",
            "token": "xxxxx",
            "patchCert": "xxxxx"
        },
        {
            "accessory": "SamsungAirconditioner",
            "name": "Climatizzatore5",
            "ip": "192.168.1.15",
            "token": "xxxxx",
            "patchCert": "xxxxx"
        },
        {
            "accessory": "SamsungAirconditioner",
            "name": "Climatizzatore4",
            "ip": "192.168.1.16",
            "token": "xxxx",
            "patchCert": "xxxxx"
        },
        {
            "accessory": "SamsungAirconditioner",
            "name": "Climatizzatore3",
            "ip": "192.168.1.18",
            "token": "xxxxx",
            "patchCert": "xxxxx"
        },
        {
            "accessory": "OutdoorTemp",
            "name": "TemperaturaEsterna2",
            "ip": "192.168.1.16",
            "token": "xxxx",
            "patchCert": "xxxxx"
        },
        {
            "accessory": "OutdoorTemp",
            "name": "TemperaturaEsterna",
            "ip": "192.168.1.17",
            "token": "xxxx",
            "patchCert": "xxxxx"
        }
    ],
    "platforms": [
        {
            "name": "Camera FFmpeg",
            "cameras": [
                {
                    "name": "camera",
                    "motion": true,
                    "manufacturer": "Tapo",
                    "model": "C200",
                    "doorbell": false,
                    "switches": true,
                    "motionTimeout": 30,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-re -i rtsp://xxxx:xxxx@192.168.1.10:554/stream1",
                        "stillImageSource": "-re -i rtsp://xxxx:xxxx@192.168.1.10:554/stream1",
                        "maxStreams": 2,
                        "maxFPS": 24,
                        "forceMax": true,
                        "vcodec": "h264_omx",
                        "packetSize": 376,
                        "audio": false
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },
        {
            "platform": "TAPO-CAMERA",
            "cameras": [
                {
                    "name": "camera",
                    "ipAddress": "192.168.1.10",
                    "password": "XXXXX",
                    "streamPassword": "xxxxxx",
                    "streamUser": "xxxxx",
                    "pullInterval": 60000,
                    "debug": true,
                    "disableStreaming": false,
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false,
                    "lowQuality": false
                }
            ]
        },
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        }
    ]
}

**Comment by kopiro** [comment]
Your config looks ok; do you see this plugin in the "Plugins" section?
It looks like homebridge is not able to find the plugin

**Comment by cicciovo** [comment]
Yes, sure! I see the plugin! Correct, homebridge isn't able to find the plugin. Why?

**Comment by kopiro** [comment]
Can you post the output of:

```sh
npm -g list | grep homebridge-tapo-camera
```

**Comment by cicciovo** [comment]
pi@raspberrypi:~ $ npm -g list | grep homebridge-tapo-camera
├── homebridge-tapo-camera@1.5.2

**Comment by kopiro** [comment]
Everything looks correct; have you already tried to reboot homebridge and give a restart the raspberry?

**Comment by kopiro** [comment]
Also, do you see this in the logs?

```
[11/23/2021, 12:32:48 PM] Loaded plugin: homebridge-tapo-camera@1.5.2
[11/23/2021, 12:32:48 PM] Registering platform 'homebridge-tapo-camera.TAPO-CAMERA'
```

**Comment by cicciovo** [comment]
12:34:55] No plugin was found for the platform "TAPO-CAMERA" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by cicciovo** [comment]
I don't know why?...

**Comment by kopiro** [comment]
Do you see any other logs related to this? Try to post the full logs after restart and we'll check why the plugin is not being loaded.

**Comment by cicciovo** [comment]
I'm lookin for every where, but not else.
[23/11/2021, 12:34:40] [Homebridge UI] Homebridge restart request received
[23/11/2021, 12:34:41] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[23/11/2021, 12:34:41] [Homebridge UI] Sending SIGTERM to Homebridge
[23/11/2021, 12:34:41] Got SIGTERM, shutting down Homebridge...
[23/11/2021, 12:34:46] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[23/11/2021, 12:34:51] [HB Supervisor] Restarting Homebridge...
[23/11/2021, 12:34:51] [HB Supervisor] Starting Homebridge with extra flags: -I
[23/11/2021, 12:34:51] [HB Supervisor] Started Homebridge v1.3.6 with PID: 2793
[23/11/2021, 12:34:52] Loaded config.json with 9 accessories and 3 platforms.
[23/11/2021, 12:34:52] Loaded 0 cached accessories from cachedAccessories.
[23/11/2021, 12:34:52] ---
[23/11/2021, 12:34:55] Loaded plugin: homebridge-camera-ffmpeg@3.1.3
[23/11/2021, 12:34:55] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[23/11/2021, 12:34:55] ---
[23/11/2021, 12:34:55] Loaded plugin: homebridge-config-ui-x@4.41.2
[23/11/2021, 12:34:55] Registering platform 'homebridge-config-ui-x.config'
[23/11/2021, 12:34:55] ---
[23/11/2021, 12:34:55] Loaded plugin: homebridge-mqtt@1.0.1
homebridge API version: 2.7
[23/11/2021, 12:34:55] Registering platform 'homebridge-mqtt.mqtt'
[23/11/2021, 12:34:55] ---
[23/11/2021, 12:34:55] Loaded plugin: homebridge-samsung-airconditioner@0.1.0
[23/11/2021, 12:34:55] Registering accessory 'homebridge-samsung-airconditioner.SamsungAirconditioner'
[23/11/2021, 12:34:55] ---
[23/11/2021, 12:34:55] Loaded plugin: homebridge-samsung-outdoorTemp@0.2.2
[23/11/2021, 12:34:55] Registering accessory 'homebridge-samsung-outdoorTemp.OutdoorTemp'
[23/11/2021, 12:34:55] ---
[23/11/2021, 12:34:55] ====================
[23/11/2021, 12:34:55] ERROR LOADING PLUGIN homebridge-samsung-power:
[23/11/2021, 12:34:55] Error: Cannot find module 'sqlite3'
Require stack:
- /home/pi/homebridge-samsung-power/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/pi/homebridge-samsung-power/index.js:6:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[23/11/2021, 12:34:55] ====================
[23/11/2021, 12:34:55] Loading 3 platforms...
[23/11/2021, 12:34:55] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[23/11/2021, 12:34:55] No plugin was found for the platform "TAPO-CAMERA" in your config.json. Please make sure the corresponding plugin is installed correctly.
[23/11/2021, 12:34:55] [Config] Initializing config platform...
[23/11/2021, 12:34:55] [Config] Running in Service Mode
[23/11/2021, 12:34:55] Loading 9 accessories...
[23/11/2021, 12:34:55] [Climatizzatore] Initializing SamsungAirconditioner accessory...
[23/11/2021, 12:34:55] No plugin was found for the accessory "SamsungPowerConsumption" in your config.json. Please make sure the corresponding plugin is installed correctly.
[23/11/2021, 12:34:55] No plugin was found for the accessory "SamsungPowerConsumption" in your config.json. Please make sure the corresponding plugin is installed correctly.
[23/11/2021, 12:34:55] [Climatizzatore2] Initializing SamsungAirconditioner accessory...
[23/11/2021, 12:34:55] [Climatizzatore5] Initializing SamsungAirconditioner accessory...
[23/11/2021, 12:34:55] [Climatizzatore4] Initializing SamsungAirconditioner accessory...
[23/11/2021, 12:34:55] [Climatizzatore3] Initializing SamsungAirconditioner accessory...
[23/11/2021, 12:34:55] [TemperaturaEsterna2] Initializing OutdoorTemp accessory...
[23/11/2021, 12:34:55] [TemperaturaEsterna] Initializing OutdoorTemp accessory...
[23/11/2021, 12:34:55] [Camera FFmpeg] [camera] Configuring unbridged accessory...
Setup Payload:
X-HM://0023ISYWY0KK9
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[23/11/2021, 12:34:55] camera 8A75 is running on port 33673.
[23/11/2021, 12:34:55] Please add [camera 8A75] manually in Home app. Setup Code: 031-45-154
[23/11/2021, 12:34:55] Homebridge v1.3.6 (HAP v0.9.7) (Homebridge) is running on port 33441.

And then there are the log of my plugin... Samsungairconditioner

Ps: camera 8A75 is added...

**Comment by kopiro** [comment]
The problem could be that `homebridge-samsung-power` is causing the entire plugin loading stack to throw errors; can you try to fix the `sqlite` problem or temporarly removing that?

**Comment by cicciovo** [comment]
good news:
Homebridge v1.3.6 (HAP v0.9.7) (Homebridge) is running on port 33441.
[23/11/2021, 12:47:13] Error: Accessory camera experienced an address collision.
    at BridgeService.handlePublishExternalAccessories (/usr/lib/node_modules/homebridge/src/bridgeService.ts:419:15)
[23/11/2021, 12:47:13] Got SIGTERM, shutting down Homebridge...

**Comment by cicciovo** [comment]
Got SIGTERM, shutting down Homebridge...
[23/11/2021, 12:49:14] Error: You should create pull-point subscription first!
    at Cam.pullMessages (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:188:10)
    at Cam._eventPull (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:309:9)
    at Cam.<anonymous> (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:100:13)
    at parseSOAPString (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/utils.js:108:3)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/cam.js:246:4)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[23/11/2021, 12:49:18] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[23/11/2021, 12:49:23] [HB Supervisor] Restarting Homebridge...
[23/11/2021, 12:49:23] [HB Supervisor] Starting Homebridge with extra flags: -I
[23/11/2021, 12:49:23] [HB Supervisor] Started Homebridge v1.3.6 with PID: 3552
[23/11/2021, 12:49:25] Loaded config.json with 7 accessories and 3 platforms.
[23/11/2021, 12:49:25] Loaded 0 cached accessories from cachedAccessories.
[23/11/2021, 12:49:25] ---
[23/11/2021, 12:49:27] Loaded plugin: homebridge-camera-ffmpeg@3.1.3
[23/11/2021, 12:49:27] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[23/11/2021, 12:49:27] ---
[23/11/2021, 12:49:27] Loaded plugin: homebridge-config-ui-x@4.41.2
[23/11/2021, 12:49:27] Registering platform 'homebridge-config-ui-x.config'
[23/11/2021, 12:49:27] ---
[23/11/2021, 12:49:27] Loaded plugin: homebridge-mqtt@1.0.1
homebridge API version: 2.7
[23/11/2021, 12:49:27] Registering platform 'homebridge-mqtt.mqtt'
[23/11/2021, 12:49:27] ---
[23/11/2021, 12:49:27] Loaded plugin: homebridge-samsung-airconditioner@0.1.0
[23/11/2021, 12:49:27] Registering accessory 'homebridge-samsung-airconditioner.SamsungAirconditioner'
[23/11/2021, 12:49:27] ---
[23/11/2021, 12:49:27] Loaded plugin: homebridge-samsung-outdoorTemp@0.2.2
[23/11/2021, 12:49:27] Registering accessory 'homebridge-samsung-outdoorTemp.OutdoorTemp'
[23/11/2021, 12:49:27] ---
[23/11/2021, 12:49:28] Loaded plugin: homebridge-tapo-camera@1.5.2
[23/11/2021, 12:49:28] Registering platform 'homebridge-tapo-camera.TAPO-CAMERA'
[23/11/2021, 12:49:28] ---
[23/11/2021, 12:49:28] Loading 3 platforms...
[23/11/2021, 12:49:28] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[23/11/2021, 12:49:28] [TAPO-CAMERA] Initializing TAPO-CAMERA platform...
[23/11/2021, 12:49:28] [Config] Initializing config platform...
[23/11/2021, 12:49:28] [Config] Running in Service Mode
[23/11/2021, 12:49:28] Loading 7 accessories...
[23/11/2021, 12:49:28] [Climatizzatore] Initializing SamsungAirconditioner accessory...
[23/11/2021, 12:49:28] [Climatizzatore2] Initializing SamsungAirconditioner accessory...
[23/11/2021, 12:49:28]

**Comment by kopiro** [comment]
Is the username and password correct, double check everything.

You should create those credentials from the TAPO camera app

**Comment by cicciovo** [comment]
Yes, i create it, the password is correct

**Comment by cicciovo** [comment]
Maybe there is a problem with onvif?

**Comment by cicciovo** [comment]
Solved! -.- the problem was more simply than it seems!
