### ISSUE TITLE
Type Error 

### ISSUE THREAD

**Issue by buzyjess** [kopiro/homebridge-tapo-camera#20]
Hello 

I am getting the below error when I tried to config TAPO camera. 

Below is my config entry : 
       {
            "platform": "TAPO-CAMERA",
            "cameras": [
                {
                    "name": "Adamo"
                }
            ]
        }

I can avoid this error if I removed hyphen '-' from TAPO-CAMERA , but it shows a new error saying the plug in missing.

[12/5/2021, 9:19:37 PM] [Config] Initializing config platform...
[12/5/2021, 9:19:37 PM] [Config] Running in Service Mode
[12/5/2021, 9:19:37 PM] [TAPO-CAMERA] Initializing TAPO-CAMERA platform...
[12/5/2021, 9:19:37 PM] TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at new TAPOCamera (/usr/local/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:25:8)
    at new CameraAccessory (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:60:19)
    at /usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:34:7
    at Array.forEach (<anonymous>)
    at CameraPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:33:25)
    at HomebridgeAPI.emit (node:events:390:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)

**Comment by kopiro** [comment]
Hi; from what I see that config is missing several required parameters, like ipAddress and user/password

**Comment by buzyjess** [comment]
thanks.. That seems to be the issue, the error was somehow misleading. 

Do we need to do anything extra for microphone and motion sensor, I cant activate them.

**Comment by kopiro** [comment]
No, the motion sensor is active by default.
