### ISSUE TITLE
Type Error - please help

### ISSUE THREAD

**Issue by adamjb85** [kopiro/homebridge-tapo-camera#21]
Hi,

I have tried several times to set this up but keep getting this error:

TypeError: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at Hash.update (node:internal/crypto/hash:105:11)
    at Object.generate (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/uuid.ts:11:11)
    at new CameraAccessory (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:53:35)
    at /homebridge/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:34:7
    at Array.forEach (<anonymous>)
    at CameraPlatform.didFinishLaunching (/homebridge/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:33:25)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)

This is my config (have left out the specific details):

{
    "platform": "TAPO-CAMERA",
    "cameras": [
        {
            "name": "Adamo",
            "ipAddress": "IP Address",
            "password": "Tapo Password",
            "streamPassword": "StreamPassword!",
            "streamUser": "Stream User email",
            "pullInterval": 60000,
            "debug": false,
            "disableStreaming": false,
            "disablePrivacyAccessory": false,
            "disableAlarmAccessory": false,
            "disableMotionAccessory": false,
            "lowQuality": false
        },
        {}
    ]
}

Please help, don't know what I'm doing wrong? Thanks Adam.

**Comment by kopiro** [comment]
Can you please remive the empty configuration at the bottom? The leading {}

**Comment by adamjb85** [comment]
Ok, would you be able to provide the exact code please so I can copy and paste it as I’m still getting the error? Thanks
________________________________

Adam Brown
Director
t. 08 8271 3366
m. 0432 853 558
www.wellconn.com.au

**Comment by kopiro** [comment]
```
 {
 "platform": "TAPO-CAMERA",
 "cameras": [
 {
 "name": "Adamo",
 "ipAddress": "IP Address",
 "password": "Tapo Password",
 "streamPassword": "StreamPassword!",
 "streamUser": "Stream User email",
 "pullInterval": 60000,
 "debug": false,
 "disableStreaming": false,
 "disablePrivacyAccessory": false,
 "disableAlarmAccessory": false,
 "disableMotionAccessory": false,
 "lowQuality": false
 },
]
```
