### ISSUE TITLE
ONVIF SOAP Fault: Authority failure help

### ISSUE THREAD

**Issue by sluggg** [kopiro/homebridge-tapo-camera#27]
Fixed this it’s me being a tool and inputting my stream passcode incorrectly.
when I select the camera in the home app it just shows a still image with the loading buffering circle overplayed?
I now also have two instances of the same camera in my home all the old one which crashes the home app if tapped and the new one which works as expected. Does anyone know how to remove the instance that crashes if tapped? 

Thanks for help

Set up this as my 5th homebridge module and had no issues previously, stumped trying to fix this Ive gone through the other issues and double checked my config

Config:
{
            "platform": "TAPO-CAMERA",
            "cameras": [
                {
                    "name": "SnoutCam",
                    "ipAddress": "192.168.X.XXX",
                    "password": "XXxXXxXXxXX",
                    "streamPassword": "fXXxXXxXXxXX",
                    "streamUser": "User",
                    "pullInterval": 60000,
                    "disableStreaming": false,
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false,
                    "lowQuality": false,
                    "debug": true
                }
            ]
        }

Error
node:4042) UnhandledPromiseRejectionWarning: Error: ONVIF SOAP Fault: Authority failure
    at /usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/utils.js:101:13
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:400:28)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:5:59)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4042) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4042) UnhandledPromiseRejectionWarning: Error: ONVIF SOAP Fault: Authority failure
    at /usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/utils.js:101:13
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:400:28)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:5:59)
(node:4042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4042) UnhandledPromiseRejectionWarning: Error: ONVIF SOAP Fault: Authority failure
    at /usr/lib/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/utils.js:101:13
    at Parser.<anonymous> (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:304:18)
    at Parser.emit (events.js:400:28)
    at SAXParser.onclosetag (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:262:26)
    at emit (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:323:31)
    at Parser.parseString (/usr/lib/node_modules/homebridge-tapo-camera/node_modules/xml2js/lib/parser.js:5:59)
(node:4042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by sluggg** [comment]
Fixed this it’s me being a tool and inputting my stream passcode incorrectly.
I now have two instances of the same camera in my home all the old one which crashes the home app if tapped and the new one which works as expected. Does anyone know how to remove the instance that crashes if tapped? Thanks for help
