### ISSUE TITLE
random camera error

### ISSUE THREAD

**Issue by drlkp** [kopiro/homebridge-tapo-camera#66]
**Describe Your Problem:**
<during day randomly an error appear ->

**Logs:**
[03/11/2022, 17:37:20] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Camera replied with error
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:253:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:206:7)

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by drlkp** [comment]
add another issue, the above Starts with this:[tapo-camera] Reset token. error_code:  -40401
