### ISSUE TITLE
Update C210 FW to 1.3.9 error message "Invalid cloud password" appears

### ISSUE THREAD

**Issue by iamxuans** [kopiro/homebridge-tapo-camera#90]
I updated my Tapo C210 camera to version 1.3.9. After that, the integration could no longer connect to the camera. Ihave other two C210 stay on FW 1.3.7 are fine. Could you help to fix this problem?

Error at 'getStatusAndUpdateCharacteristics'. Error: Unable to find token in response, probably your credentials are not valid. Please make sure you set your TAPO Cloud password
    at TAPOCamera.fetchToken (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:72:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.tokenPromise (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:96:23)
    at TAPOCamera.getTAPOCameraAPIUrl (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:107:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:133:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:228:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at CameraAccessory.setup (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:259:7)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:30:9

**Comment by rgavril** [comment]
I have the same problem, running the same firmware version : 1.3.9

As a temporary workaround I "enabled" this options for the camera:
 - Disable Privacy
 - Disable Alarm
 - Disable Motion

This way the plugin avoids using the api token and ,at least, get the video stream available.

**Comment by PedrooMR** [comment]
Hello, I have the same issue.

**Comment by FrancoisDucrot** [comment]
Hi,
Same problem here, any update ?

**Comment by adamb3ll** [comment]
1.3.9 has changed the http requests to the camera. 

The request has change from a user and password, to what looks like two login calls, the first with a cnonce receiving back a "device_confirm" that appears to be different each time, and a "key" that looks consistent.  The second login then uses the same cnonce and a "digest_passwd".  No idea what they use to generate that.

**Comment by MarrinerK** [comment]
In an attempt to offer some more context, this is my experience

I have 3 C310 cameras - 2 reporting to be Hardware Version 2.0, 1 Hardware Version 1.0

One of the Version 1 cameras have auto updated its firmware to v 1.3.9 Build 231024 Rel.73362n(4555). The other to v 1.3.9 Build 231024 Rel.62920n(4555)

The Version 2 camera is on v 1.3.7 Build 230714 Rel.47798n (4555) and will not do a firmware update either manually or auto

All three are working as expected through Taco iOS app and via NX-V on a Mac using the (unchanged) log-in details (as used by HB).

Only the two Version 1 cameras are available via HB. The console issues reported are:

[11/15/2023, 1:20:38 PM] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unable to find token in response, probably your credentials are not valid. Please make sure you set your TAPO Cloud password
    at TAPOCamera.fetchToken (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:72:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.tokenPromise (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:96:23)
    at TAPOCamera.getTAPOCameraAPIUrl (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:107:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:133:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:228:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at CameraAccessory.setup (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:259:7)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:30:9
[11/15/2023, 1:20:38 PM] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unable to find token in response, probably your credentials are not valid. Please make sure you set your TAPO Cloud password
    at TAPOCamera.fetchToken (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:72:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.tokenPromise (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:96:23)
    at TAPOCamera.getTAPOCameraAPIUrl (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:107:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:133:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:228:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at CameraAccessory.setup (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:259:7)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:30:9

**Comment by letens** [comment]
same issue here ... disabling Privacy / Alarm / Motion works a bit but error keeps on appearing

**Comment by kopiro** [comment]
Hello folks, I'll focus this weekend on trying to understand if there is a way to re reverse-engineer the way the token exchange works.

**Comment by kopiro** [comment]
Hey folks, unfortunately my camera latest firmware is still 1.3.6, there's no update available.
I can try to check if someone wrote a new library that already fixes this issue and trying to replicate the same behaviour, but without a test device it's impossible for me to test it and be reactive.

**Comment by MarrinerK** [comment]
Update from me

The camera that was HW v2 and seemingly stuck on 1.3.7 has now updated to 1.3.9. After removing it and adding back to Home it now works through HB as expected.

Still have the error messages in the console but functionally things seem to have improved.

**Comment by adppark** [comment]
I also have same issue.
C100 is HW v1 and fw 1.3.9 and C200 is HW v1 and fw 1.3.9
Streaming works when you click on the screen, but it returns to a no-response state. The privacy mode switch does not operate with no response.
I hope this problem will be solved as soon as possible..

**Comment by iamxuans** [comment]
How could we help you to verify the solution?
> Hey folks, unfortunately my camera latest firmware is still 1.3.6, there's no update available. I can try to check if someone wrote a new library that already fixes this issue and trying to replicate the same behaviour, but without a test device it's impossible for me to test it and be reactive.

**Comment by makraip** [comment]
HA guys solved the new authentication coming with 1.3.9, maybe it helps:
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control

**Comment by Fabuloulou** [comment]
Hello,
Same problem with one of my TAPO C200 cameras with 1.3.9 firmware. 
No privacy mode changes possible with this firmware.

My second C200 is still with 1.3.6 firmware and work fine withour error.

**Comment by TA2k** [comment]
Here is the flow for the new firmware in python
https://github.com/JurajNyiri/pytapo/blob/5e7df7d0e05065d2f04990cb1db0a2cd75d13775/pytapo/__init__.py#L301

**Comment by kopiro** [comment]
This is very good, thank you.
I'll try to implement it tomorrow!

**Comment by kopiro** [comment]
Alright it actually looks like I can now update to 1.3.9, let's see :)

**Comment by kopiro** [comment]
https://github.com/JurajNyiri/pytapo/pull/82/files

**Comment by kopiro** [comment]
Ongoing PR: https://github.com/kopiro/homebridge-tapo-camera/pull/94

**Comment by kopiro** [comment]
https://github.com/kopiro/homebridge-tapo-camera/releases/tag/v2.3.0

**Comment by iamxuans** [comment]
Thanks!!

**Comment by Fabuloulou** [comment]
Hi,
After update to 2.3.1, I have this error :
[homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unknown password encryption method
    at TAPOCamera.getHashedPassword (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:88:13)
    at TAPOCamera.refreshStok (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:175:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:339:19)
    at /homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:419:23
    at TAPOCamera.getStatus (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:559:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at CameraAccessory.setup (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:265:7)
    at /homebridge/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:30:9

on my 2 cameras with 1.3.6 and 1.3.9 firmwares

**Comment by kopiro** [comment]
@Fabuloulou does this happen on both cameras? Can you share more logs after having enabled debug logs and making sure you redact sensitive informations?

**Comment by Fabuloulou** [comment]
yes same problem on both cameras.
After activate debug in the setting for both cameras, no more log appears in homebridge console. 
<img width="366" alt="Capture d’écran 2023-11-29 à 13 51 00" src="https://github.com/kopiro/homebridge-tapo-camera/assets/36621445/fd9f9c81-df34-46da-a986-fef52d4cf9a0">

**Comment by Fabuloulou** [comment]
i have a few more logs :
`[11/29/2023, 2:01:29 PM] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unknown password encryption method
    at TAPOCamera.getHashedPassword (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:88:13)
    at TAPOCamera.refreshStok (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:175:28)
    at TAPOCamera.getAuthenticatedAPIURL (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:339:19)
    at /homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:419:23
    at TAPOCamera.getStatus (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:559:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)

/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:309
                                callback.call(this, err, data, xml);
             ^
TypeError: callback.call is not a function
    at Cam.<anonymous> (/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/events.js:309:14)
    at ClientRequest.<anonymous> (/homebridge/node_modules/homebridge-tapo-camera/node_modules/onvif/lib/cam.js:328:4)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketErrorListener (node:_http_client:502:9)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[11/29/2023, 2:01:49 PM] [homebridge-tapo-camera] Child bridge process ended
[11/29/2023, 2:01:49 PM] [homebridge-tapo-camera] Process Ended. Code: 1, Signal: null
[11/29/2023, 2:01:56 PM] [homebridge-tapo-camera] Restarting Process...
[11/29/2023, 2:01:58 PM] [homebridge-tapo-camera] Launched child bridge with PID 5854
[11/29/2023, 2:01:59 PM] Registering platform 'homebridge-tapo-camera.tapo-camera'
[11/29/2023, 2:01:59 PM] [homebridge-tapo-camera] Loaded homebridge-tapo-camera v2.3.1 child bridge successfully
[11/29/2023, 2:01:59 PM] Loaded 0 cached accessories from cachedAccessories.XXXX.
[11/29/2023, 2:01:59 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-tapo-camera) is running on port 58528.
[11/29/2023, 2:02:01 PM] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unknown password encryption method
    at TAPOCamera.getHashedPassword (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:88:13)
    at TAPOCamera.refreshStok (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:175:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:339:19)
    at /homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:419:23
    at TAPOCamera.getStatus (/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:559:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at CameraAccessory.setup (/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:265:7)
    at /homebridge/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:30:9
[11/29/2023, 2:02:01 PM] Sejour CE0E is running on port 44335.
[11/29/2023, 2:02:01 PM] Please add [Sejour CE0E] manually in Home app. Setup Code: XXX`

**Comment by kopiro** [comment]
You need to put the whole homebridge in Debug mode
