### ISSUE TITLE
After update Raspberry and homebirdge

### ISSUE THREAD

**Issue by entoryFB** [kopiro/homebridge-tapo-camera#91]
[19/11/2023, 10:42:42] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. TypeError: Cannot read properties of undefined (reading 'find')
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:256:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:206:7)

**Comment by lebence** [comment]
same here!

**Comment by Rene1695** [comment]
Same for me

**Comment by Rene1695** [comment]
But the video stream is still working in HomeKit. Its just the error log in home bridge

**Comment by guile54** [comment]
Same Issue Poppin every minutes:
`[22/11/2023` 22:31:27] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unable to find token in response, probably your credentials are not valid. Please make sure you set your TAPO Cloud password
    at TAPOCamera.fetchToken (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:72:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.tokenPromise (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:96:23)
    at TAPOCamera.getTAPOCameraAPIUrl (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:107:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:133:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:228:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:228:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:206:7)``

OS	Ubuntu Jammy Jellyfish (22.04.3 LTS)
Version de Node.js	 v18.18.2
tapo plugin version 2.2.3

**Comment by markuzkuz** [comment]
Same for me, it's not working anymore because of the " Error at 'getStatusAndUpdateCharacteristics'. Error: Unable to find token in response, probably your credentials are not valid." 

Thank you for your time working on it! :)

**Comment by entoryFB** [comment]
The error has been fixed since the last update, but now the error message appears
FFmpeg issue
