### ISSUE TITLE
Error at 'getStatusAndUpdateCharacteristics'. Error: Unknown password encryption method

### ISSUE THREAD

**Issue by anjuchamantha** [kopiro/homebridge-tapo-camera#97]
**Describe The Bug:**
I have a Tapo C210 camera.
This error is in homebridge logs. But the camera is working in homekit. Motion Detection working. Alarm and Eyes not working (No Response)

**Logs:**

```
[tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unknown password encryption method
    at TAPOCamera.getHashedPassword (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:88:13)
    at TAPOCamera.refreshStok (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:175:28)
    at TAPOCamera.getAuthenticatedAPIURL (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:339:19)
    at /var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:419:23
    at TAPOCamera.getStatus (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:559:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)
```

**Plugin Config:**

```json
{
            "cameras": [
                {
                    "name": "<Name>",
                    "ipAddress": "<IP>",
                    "password": "<AccountPW>",
                    "streamUser": "<StreamUserName>",
                    "streamPassword": "<StreamPW>",
                    "disableStreaming": false,
                    "disablePrivacyAccessory": false,
                    "disableAlarmAccessory": false,
                    "disableMotionAccessory": false,
                    "lowQuality": false
                }
            ],
            "platform": "tapo-camera"
        },
```

**Screenshots:**

![Screenshot 2023-11-30 132009](https://github.com/kopiro/homebridge-tapo-camera/assets/42867633/2c472381-b4d5-4d66-8b16-99e66e530e03)

**Environment:**

* **Plugin Version**: v2.3.1
* **Homebridge Version**: v1.6.1
* **Node.js Version**: v18.16.0
* **NPM Version**: 
* **Operating System**: Raspbian GNU/Linux Bullseye (11)

**Comment by anjuchamantha** [comment]
Never mind. Working all as expected after firmware update in camera

**Comment by ppapajohn** [comment]
Unfortunately I cannot get it to work as well. C320WS, latest firmware and plugin version installed, and the child bridge is on an infinite loop of restarts with the following error messages: 

[12/1/2023, 7:50:22 PM] [homebridge-tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unknown password encryption method
    at TAPOCamera.getHashedPassword (/usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:88:13)
    at TAPOCamera.refreshStok (/usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:175:28)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:337:19)
    at /usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:417:23
    at TAPOCamera.getStatus (/usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:557:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/usr/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at CameraAccessory.setup (/usr/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:265:7)
    at /usr/lib/node_modules/homebridge-tapo-camera/src/cameraPlatform.ts:30:9


Anything I am doing wrong? I know this bug is closed as #91 is on the same topic, but I wouldn't want to create a new one and create unnecessary noice. 

Thanks! 

Panos

**Comment by ppapajohn** [comment]
Correction: 1 camera has a new firmware (1.1.6), while the other one is still waiting for TAPO to push it and is stuck on 1.0.1...

**Comment by x23piracy** [comment]
Hi,

i have a C200 and still have to problem on 2.3.2

[3.12.2023, 16:25:44] [tapo-camera] Error at 'getStatusAndUpdateCharacteristics'. Error: Unknown password encryption method
    at TAPOCamera.getHashedPassword (/usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:88:13)
    at TAPOCamera.refreshStok (/usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:175:28)
    at TAPOCamera.getAuthenticatedAPIURL (/usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:337:19)
    at /usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:417:23
    at TAPOCamera.getStatus (/usr/lib/node_modules/homebridge-tapo-camera/src/tapoCamera.ts:557:18)
    at CameraAccessory.getStatusAndUpdateCharacteristics (/usr/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:234:27)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-tapo-camera/src/cameraAccessory.ts:212:7)


Best Regards X23
